Content:
    modelib_moose:
        root_dir: doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - contrib/**
            - css/**
            - js/**

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: Modelib_MOOSE

Extensions:
    appsyntax:
        type: MooseDocs.extensions.appsyntax
        executable: ${ROOT_DIR}
        includes:
            - include
